### ISSUE TITLE
3. User can view product detail

### ISSUE THREAD

**Issue by stevebrownlee** [illegal-llamas/djangazon#14]
**Product ticket by [stevebrownlee](https://github.com/stevebrownlee)**

----

**Product ticket by [stevebrownlee](https://github.com/stevebrownlee)**

----

**Given** user is viewing any page that contains a hyperlink for a product
**When** user performs a gesture on the product hyperlink
**Then** user will be shows the product detail page containing title, description, quantity available,  price/unit, and a button labeled *Add to Order*

Tests required for this product ticket:
- Verify that when a product is created that the Product Detail view has the correct product in the response context
- Verify that when a product is created that the Product Detail view has the title, description, price and quantity are in the response body

**Comment by sarawithad** [comment]
This ticket also serves as "User can add product to order" ticket.
