### ISSUE TITLE
User can search products to buy

### ISSUE THREAD

**Issue by stevebrownlee** [illegal-llamas/djangazon#4]
**Product ticket by [stevebrownlee](https://github.com/stevebrownlee)**

----

**Product ticket by [stevebrownlee](https://github.com/stevebrownlee)**

----

**Given** the user is authenticated
**When** the user clicks on the search input field in the navigation bar
**And** the user types the name of a product
**When** pressed the enter key
**Then** products matching the keyword show in the page

**Comment by sarawithad** [comment]
User does NOT have to be authenticated to search products.
